export const POSTS = 'POSTS';

export const FETCH_POSTS = 'FETCH_POSTS';
export const DISMISS_POST = 'DISMISS_POST';
export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
export const DISMISS_ALL_POSTS = 'DISMISS_ALL_POSTS';
